name: Next js build with Caching & Artifacts

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@6.0.1

      - name: Setup Node JS
        uses: actions/setup-node@6.1.0
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Install Dependencies
        run: npm install

      - name: Build Next Js App
        run: npm run build

      - name: Upload Build on Artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: nextjs-build
          path: out/
